Cd/Ls implemented.
tehnar/spbau-software-design-practice pull request #3
Opened 2016-10-02 22:35 UTC by Rebryk

* Код понятен и хорошо читаемый. 
* Почти у каждого метода есть словесное описание.
* Присутствует большее кол-во тестов.

При добавлении новых команд, никаких сложностей не возникло.

2016-10-17 12:29 UTC, yurii-litvinov requested changes

2016-10-17 12:29 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/softwaredesign/commands/CdCommand.kt
> +                env.setCurrentDirectory(file.absolutePath)
При таком подходе все внешние команды не будут знать про изменение директории, да и все внутренние команды должны про это знать и учитывать (cat Вы поправили, а, например, pwd игнорирует результаты cd). Выставлять user.dir несколько лучше (хотя тоже не надёжно). В любом случае, лучше описать в документации и/или комментариях желаемое поведение команд относительно currentDirectory и стараться ему следовать.

2016-10-25 21:50 UTC, Rebryk commented
@yurii-litvinov подправил.

2016-12-19 09:34 UTC, Rebryk commented
@yurii-litvinov
Проверьте, плиз

2016-12-27 15:17 UTC, yurii-litvinov approved these changes

2020-08-02 17:39 UTC, closed without merging